### ISSUE TITLE
Result out of bounds

### ISSUE THREAD

**Issue by jonathanbull** [asimlqt/Euclidean-Distance-Score#1]
I get a result of '9.99900009999E-5' if I pass the following data:

```
$reviews = array(
    'Tania Diede' => array(
        'The Mozart Conspiracy' => 800,
    ),
    'Allan Rhein' => array(
        'The Mozart Conspiracy' => 900,
    ),
);
```

I believe this is incorrect, as the value should fall between the bounds of 0 and 1?

**Comment by asimlqt** [comment]
That number is in fact between 0 and 1! it's 0.0000999900009999. That's just how large floating point numbers are displayed by computers.

To be honest it might not be the best algorithm for your use case. Either try using smaller numbers such as between 1 and 10 or look around for a better algorithm.

Sorry, that's all i can say.

**Comment by jonathanbull** [comment]
You're quite right, I must have had a mental blip that day. Thanks for responding.
